### ISSUE TITLE
[FALSE POSITIVE] Malwarebytes flags EXE file as malware

### ISSUE THREAD

**Issue by robinhood2014** [Lateralus138/hosts-compress-windows#3]
After hearing about yet another vulnerability in Windows, I decided to boost my Internet security by downloading and installing Malwarebytes. When I ran my first scan, Malwarebytes flagged two files as malware -- hostscompress-x64.exe, and a modified version of Steven Black's hosts file which I compressed using the same. I've never had any malware problems using these files before, so why is Malwarebytes choosing _now_ to warn me about what I believe to be a false positive? I'm enclosing the scan log.
[false-positive.txt](https://github.com/user-attachments/files/15848253/false-positive.txt)

**Comment by Lateralus138** [comment]
Thank you for bringing this to my attention @robinhood2014, but yes, this is most certainly a false positive.

All of my source files and my build files are available for scrutiny by the public here at this repository and anyone who can look can see there are no external resources being inserted at build time. Everything at this repository is stored and built here and all logs are available for every action taken.

My assumption is that because of the very nature and capability of this program (altering a secure system file and directly at that) it is flagged. This is not surprising. I have nothing to hide.

There is no network capability in this tool and the only file it creates (and/or alters) is the hosts file itself, which is specifically what this tool is for (of course).

Most "malware" and "virus" tools flag behavior and it is flagging the aforementioned task of altering the hosts file.
